# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.
# Project
version=2.0
group=com.carmellium
java_version=21
# Common
minecraft_version=1.21
mod_name=forgeshot
mod_author=
mod_id=forgeshot
license=All-Rights-Reserved
credits=
description=
minecraft_version_range=[1.21, 1.22)
neo_form_version=1.21-20240613.152323
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21
parchment_version=2024.06.23
# Forge - https://files.minecraftforge.net/net/minecraftforge/forge/index_1.21.html
forge_version=51.0.33
forge_loader_version_range=[51,)
# NeoForge - https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.0.167
neoforge_loader_version_range=[4,)
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
# CurseForge Project ID
curseforge_project_id=911710
curse_page=https://www.curseforge.com/minecraft/mc-mods/forgeshot

modrinth_project=3j0bB3uL
modrinth_page=https://modrinth.com/mod/forgeshot
